### PR TITLE
upload API

### PR DESCRIPTION
**Pull request by ZoeChenn**
學員名稱：陳柔妤
Discord 名稱：肉魚
供測試網址：
http://54.153.197.212:3000/api/attractions?page=1
http://54.153.197.212:3000/api/attractions?page=0&keyword=劍潭
http://54.153.197.212:3000/api/attractions?page=0&keyword=北
http://54.153.197.212:3000/api/attraction/10
http://54.153.197.212:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
1. `nextPage` field in http://54.153.197.212:3000/api/attractions?page=0 should be 1.
2. `nextPage` field in http://54.153.197.212:3000/api/attractions?page=4 should be null, because page 4 is the last page.
3. http://54.153.197.212:3000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should have some data there.

Leave comment in this pull request after you fixed them.

**Review by ZoeChenn — COMMENTED** [review]
已修復並更新完成，確認 1-3 皆符合需求，再麻煩老師確認，謝謝。

**Review by cwpeng — COMMENTED** [review]
Page number is started from 0, so that http://54.153.197.212:3000/api/attractions?page=1&keyword=%E5%8A%8D%E6%BD%AD should have no data, because the first page is 0 and there is no second page. Another example is http://54.153.197.212:3000/api/attractions?page=2&keyword=%E5%8C%97.

Re-request review after you fixed this issue.

**Comment by ZoeChenn** [comment]
已修復、更新完成，並再次進行需求測試，確認符合，不好意思，再麻煩老師確認。

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review again for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
