### PR TITLE
Upload week3 assignment

### PR DESCRIPTION
**Pull request by ZoeChenn**
學員：陳柔妤
http://54.153.197.212:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Keep the image box in the same size even if there are different image sizes in image slider.
2. There should have some paddings in date input.

**Comment by ZoeChenn** [comment]
I've repaired the issue. Please check it again. Thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

You can try to preload images in slider for better experience.

**Comment by ZoeChenn** [comment]
I'll try it. Thank you so much!

**Pull request merged**
