### PR TITLE
Update week2 assignment

### PR DESCRIPTION
**Pull request by ZoeChenn**
學員：陳柔妤
http://54.153.197.212:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we scroll down and up quickly, your code will load the same page multiple times.

未命名-13

**Comment by ZoeChenn** [comment]
I've add a request checker to make sure the request would not be load multiple times.
Please check it again, thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot/hard to load second page for now.

**Comment by ZoeChenn** [comment]
I've adjusted the observer. Please check it again, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
